version: 0.2

env:
  variables:
    S3_BUCKET: "/VideoConvertor/ArtifactsStoreBucket"
    DOTNET_CLI_HOME: /root
    HOME: /root  

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --version 8.0.11 --install-dir /root/.dotnet
      - export DOTNET_ROOT=/root/.dotnet
      - export PATH="/root/.dotnet:$PATH"
      - dotnet --version
      - dotnet tool install -g Amazon.Lambda.Tools      

  pre_build:
    commands:
      - echo "Restoring..."
      - dotnet restore

  build:
    commands:
      - echo "Packaging..."
      - export PATH="/root/.dotnet/tools:$PATH"
      - dotnet lambda package-ci \
          --serverless-template serverless.template \
          --output-template serverless-output.template \
          --s3-bucket $S3_BUCKET \
          --s3-prefix VideoConvertorStepFunctions

artifacts:
  files:
    - ./VideoConvertorStepFunctions/serverless-output.template
  discard-paths: yes
