version: 0.2

env:
  variables:    
    DOTNET_CLI_HOME: /root
    HOME: /root
  parameter-store:
    S3_BUCKET: "/VideoConvertor/ArtifactsStoreBucket"
    $S3_SOURCE_BUCKET_NAME: "/VideoConvertor/source-videoes-bucket-name"

phases:
  install:    
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --version 8.0.11 --install-dir /root/.dotnet
      - export DOTNET_ROOT=/root/.dotnet
      - export PATH="/root/.dotnet:$PATH"
      - export HOME=/root
      - dotnet --version
      - dotnet tool install -g Amazon.Lambda.Tools      
      - dotnet tool list -g

  pre_build:
    commands:
      - echo "Restoring..."
      - dotnet restore

  build:
    commands:
      - echo "Packaging..."
      - export PATH="/root/.dotnet/tools:$PATH"
      - export HOME=/root 
      - dotnet tool list -g
      - cd VideoConvertorStepFunctions
      - pwd
      - dotnet lambda package-ci --serverless-template serverless.template --output-template serverless-output.template --s3-bucket $S3_BUCKET --s3-prefix VideoConvertorStepFunctions --template serverless.template --verbose
  post_build:
    commands:
      - pwd
      - dir
      - aws cloudformation deploy --template-file serverless-output.template --stack-name Video-Convertor-Stack --capabilities CAPABILITY_IAM --parameter-overrides ParameterKey=BucketNameParameter,ParameterValue=S3_SOURCE_BUCKET ParameterKey=BucketNameParameter,ParameterValue=$S3_SOURCE_BUCKET_NAME 

artifacts:
  files:
    - ./VideoConvertorStepFunctions/serverless-output.template
  discard-paths: yes
